### ISSUE TITLE
Remove materialized views from UTA release

### ISSUE THREAD

**Issue by korikuzma** [biocommons/hackathon-2023#11] opened 2023-07-04 19:48 UTC
### Submitter Name

Reece Hart (@reece)

### Submitter Affiliation

MyOme

### Requested By

uta community

### Lead(s)

@reece 

### biocommons Repo

uta

### Project Details

Materialized views are essential for speed, but the current releases overuse them and result in very long build times for new users. Original issue [here](https://github.com/biocommons/uta/issues/228). In practice, the materialized views prevent users from effectively using the docker images.

### Skill Level

Intermediate

### Required Skills

Python, PostgreSQL, Docker

**Comment by jsstevenson** [comment] 2023-07-05 19:54
@reece, could you say more about why this is labeled "advanced"? Are you thinking that this issue would be more "careful pruning" (which would require some thought) rather than "removing entirely"?

**Comment by reece** [comment] 2023-07-07 01:06
@jsstevenson : You're right: this isn't hard. 

I typically write conventional views with a _v suffix. Then, if I decide that they're too slow, I rename that view to _dv ("definining view"), construct a materialized view as _mv, then recreate the _v as a simple select from the _mv in order to preserve the interface clients.

So, I recommend that we start with undoing the last change: remove tx_similarity_mv, then rename the _dv to _v, and redump uta.

**Comment by reece** [comment] 2023-09-11 03:33
Closing as a duplicate of https://github.com/biocommons/uta/issues/228 .

**Closed by reece** 2023-09-11 03:33 UTC
Labels: advanced, uta, docker, postgresql, python, high-priority
